### ISSUE TITLE
Use stdin instead of echo

### ISSUE THREAD

**Issue by kassah** [alexandrumos/cracklib_php#1]
I would think it would be far safer just to pipe the password directly into stdin on cracklib-checker than to try and escape it for an echo.

**Comment by alexandrumos** [comment]
Thanks for suggestion, I never thought on the stdin/stdout approach. I'll give it a try tomorrow.

**Comment by kassah** [comment]
How'd it go?

**Comment by alexandrumos** [comment]
I didn't managed to push the changes back then... I did it right now and I updated the README.md file, explaining how it can be used.
